# Generated by Django 5.1.4 on 2025-01-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isFake',
            new_name='is_fake',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fake_count',
            field=models.IntegerField(default=0),
        ),
    ]
