# Generated by Django 5.1.2 on 2025-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapi", "0004_blog_is_fake"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
